### ISSUE TITLE
No valid information found in api service.

### ISSUE THREAD

**Issue by Alex1s-C** [markg85/SeriesMeta#2]
**Context:** 

Trying to get any info from the tvmaze API, I tested with this code, but I can reproduce it with any request.

```js
SeriesMeta.isSeriesEnded('lucifer')
.then((data) => {
  if (data.ended == true) {
    console.log(`${data.series} has ended. The last episode was aired on ${data.date}.`)
  } else {
    console.log(`${data.series} is still being aired.`)
  }
  console.log(data)
})
.catch((error) => {
  console.log('The series you were looking for could not be found. ERROR :');
  console.log(error);
});
```

**Problem:**

I tested from different IP, with my VPN turned ON and OFF, and I always get this error.
![image](https://user-images.githubusercontent.com/38538923/87516288-7129d500-c67d-11ea-85af-2bb4172bff4d.png)

But if I go directly on the link shown in the error, i can clearly see the info. 
![image](https://user-images.githubusercontent.com/38538923/87517911-d8e11f80-c67f-11ea-9003-1718f305ea8b.png)

Same thing on Postman
![image](https://user-images.githubusercontent.com/38538923/87518485-a257d480-c680-11ea-97b0-77a504ee9fbf.png)

I didn't saw anything on the forum, so I guess it is related to me, or at least to this package ?

**Comment by markg85** [comment]
Hi @Alex1s-C, thank you for the elaborate report!

I think i know what's wrong, but that's actually because i see a windows path in there :)
This package uses the [curlrequest](https://github.com/node-js-libs/curlrequest/) package.
That package in turn relies on a system wide curl (it executes the curl command).

I'm guessing you don't have a curl executable in your path.

I'm willing to change it to something else if you provide a patch for it. It's not as trivial as just replacing it with something else.
Your fix is probably to just install curl.

**Comment by Alex1s-C** [comment]
Ok, thanks for your answer, 

I did a little more testing and the problem appeared when I switch from GitBash to the new windows Terminal, I was using Powershell and it was not working, but it works using a simple cmd .
Going back to GitBash everything is working great. And now it works everywhere even on Powershell(I don't really know why)

But it seems like everything was on my side
Thanks :)
